# MAUKA PENGGUNA

a = 10 
print (a)

# casting tipe data 
b = input (" masukkan nilai b :")
print (" nilai b adalah : " b, type (b))

c = int (input (" masukan nilai c : ") )
print (" nilai c adalah :, c,", type (c))

d = float (input ("masukan nilai d :"))
print (" nilai d adalah : ", d, type (d))

e = bool ( input (" masukan nilai e : ") )
print (" nilai e adalah :", e,  type (e))
